// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/biryanim/wb_tech_L0/internal/client/kafka.Producer -o producer_minimock.go -n ProducerMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	mm_kafka "github.com/biryanim/wb_tech_L0/internal/client/kafka"
	"github.com/gojuno/minimock/v3"
)

// ProducerMock implements mm_kafka.Producer
type ProducerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcClose          func() (err error)
	funcCloseOrigin    string
	inspectFuncClose   func()
	afterCloseCounter  uint64
	beforeCloseCounter uint64
	CloseMock          mProducerMockClose

	funcSendToDLQ          func(ctx context.Context, message *mm_kafka.DLQMessage, topic string) (err error)
	funcSendToDLQOrigin    string
	inspectFuncSendToDLQ   func(ctx context.Context, message *mm_kafka.DLQMessage, topic string)
	afterSendToDLQCounter  uint64
	beforeSendToDLQCounter uint64
	SendToDLQMock          mProducerMockSendToDLQ
}

// NewProducerMock returns a mock for mm_kafka.Producer
func NewProducerMock(t minimock.Tester) *ProducerMock {
	m := &ProducerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CloseMock = mProducerMockClose{mock: m}

	m.SendToDLQMock = mProducerMockSendToDLQ{mock: m}
	m.SendToDLQMock.callArgs = []*ProducerMockSendToDLQParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProducerMockClose struct {
	optional           bool
	mock               *ProducerMock
	defaultExpectation *ProducerMockCloseExpectation
	expectations       []*ProducerMockCloseExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProducerMockCloseExpectation specifies expectation struct of the Producer.Close
type ProducerMockCloseExpectation struct {
	mock *ProducerMock

	results      *ProducerMockCloseResults
	returnOrigin string
	Counter      uint64
}

// ProducerMockCloseResults contains results of the Producer.Close
type ProducerMockCloseResults struct {
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmClose *mProducerMockClose) Optional() *mProducerMockClose {
	mmClose.optional = true
	return mmClose
}

// Expect sets up expected params for Producer.Close
func (mmClose *mProducerMockClose) Expect() *mProducerMockClose {
	if mmClose.mock.funcClose != nil {
		mmClose.mock.t.Fatalf("ProducerMock.Close mock is already set by Set")
	}

	if mmClose.defaultExpectation == nil {
		mmClose.defaultExpectation = &ProducerMockCloseExpectation{}
	}

	return mmClose
}

// Inspect accepts an inspector function that has same arguments as the Producer.Close
func (mmClose *mProducerMockClose) Inspect(f func()) *mProducerMockClose {
	if mmClose.mock.inspectFuncClose != nil {
		mmClose.mock.t.Fatalf("Inspect function is already set for ProducerMock.Close")
	}

	mmClose.mock.inspectFuncClose = f

	return mmClose
}

// Return sets up results that will be returned by Producer.Close
func (mmClose *mProducerMockClose) Return(err error) *ProducerMock {
	if mmClose.mock.funcClose != nil {
		mmClose.mock.t.Fatalf("ProducerMock.Close mock is already set by Set")
	}

	if mmClose.defaultExpectation == nil {
		mmClose.defaultExpectation = &ProducerMockCloseExpectation{mock: mmClose.mock}
	}
	mmClose.defaultExpectation.results = &ProducerMockCloseResults{err}
	mmClose.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmClose.mock
}

// Set uses given function f to mock the Producer.Close method
func (mmClose *mProducerMockClose) Set(f func() (err error)) *ProducerMock {
	if mmClose.defaultExpectation != nil {
		mmClose.mock.t.Fatalf("Default expectation is already set for the Producer.Close method")
	}

	if len(mmClose.expectations) > 0 {
		mmClose.mock.t.Fatalf("Some expectations are already set for the Producer.Close method")
	}

	mmClose.mock.funcClose = f
	mmClose.mock.funcCloseOrigin = minimock.CallerInfo(1)
	return mmClose.mock
}

// Times sets number of times Producer.Close should be invoked
func (mmClose *mProducerMockClose) Times(n uint64) *mProducerMockClose {
	if n == 0 {
		mmClose.mock.t.Fatalf("Times of ProducerMock.Close mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmClose.expectedInvocations, n)
	mmClose.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmClose
}

func (mmClose *mProducerMockClose) invocationsDone() bool {
	if len(mmClose.expectations) == 0 && mmClose.defaultExpectation == nil && mmClose.mock.funcClose == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmClose.mock.afterCloseCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmClose.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Close implements mm_kafka.Producer
func (mmClose *ProducerMock) Close() (err error) {
	mm_atomic.AddUint64(&mmClose.beforeCloseCounter, 1)
	defer mm_atomic.AddUint64(&mmClose.afterCloseCounter, 1)

	mmClose.t.Helper()

	if mmClose.inspectFuncClose != nil {
		mmClose.inspectFuncClose()
	}

	if mmClose.CloseMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmClose.CloseMock.defaultExpectation.Counter, 1)

		mm_results := mmClose.CloseMock.defaultExpectation.results
		if mm_results == nil {
			mmClose.t.Fatal("No results are set for the ProducerMock.Close")
		}
		return (*mm_results).err
	}
	if mmClose.funcClose != nil {
		return mmClose.funcClose()
	}
	mmClose.t.Fatalf("Unexpected call to ProducerMock.Close.")
	return
}

// CloseAfterCounter returns a count of finished ProducerMock.Close invocations
func (mmClose *ProducerMock) CloseAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmClose.afterCloseCounter)
}

// CloseBeforeCounter returns a count of ProducerMock.Close invocations
func (mmClose *ProducerMock) CloseBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmClose.beforeCloseCounter)
}

// MinimockCloseDone returns true if the count of the Close invocations corresponds
// the number of defined expectations
func (m *ProducerMock) MinimockCloseDone() bool {
	if m.CloseMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CloseMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CloseMock.invocationsDone()
}

// MinimockCloseInspect logs each unmet expectation
func (m *ProducerMock) MinimockCloseInspect() {
	for _, e := range m.CloseMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to ProducerMock.Close")
		}
	}

	afterCloseCounter := mm_atomic.LoadUint64(&m.afterCloseCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CloseMock.defaultExpectation != nil && afterCloseCounter < 1 {
		m.t.Errorf("Expected call to ProducerMock.Close at\n%s", m.CloseMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcClose != nil && afterCloseCounter < 1 {
		m.t.Errorf("Expected call to ProducerMock.Close at\n%s", m.funcCloseOrigin)
	}

	if !m.CloseMock.invocationsDone() && afterCloseCounter > 0 {
		m.t.Errorf("Expected %d calls to ProducerMock.Close at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CloseMock.expectedInvocations), m.CloseMock.expectedInvocationsOrigin, afterCloseCounter)
	}
}

type mProducerMockSendToDLQ struct {
	optional           bool
	mock               *ProducerMock
	defaultExpectation *ProducerMockSendToDLQExpectation
	expectations       []*ProducerMockSendToDLQExpectation

	callArgs []*ProducerMockSendToDLQParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProducerMockSendToDLQExpectation specifies expectation struct of the Producer.SendToDLQ
type ProducerMockSendToDLQExpectation struct {
	mock               *ProducerMock
	params             *ProducerMockSendToDLQParams
	paramPtrs          *ProducerMockSendToDLQParamPtrs
	expectationOrigins ProducerMockSendToDLQExpectationOrigins
	results            *ProducerMockSendToDLQResults
	returnOrigin       string
	Counter            uint64
}

// ProducerMockSendToDLQParams contains parameters of the Producer.SendToDLQ
type ProducerMockSendToDLQParams struct {
	ctx     context.Context
	message *mm_kafka.DLQMessage
	topic   string
}

// ProducerMockSendToDLQParamPtrs contains pointers to parameters of the Producer.SendToDLQ
type ProducerMockSendToDLQParamPtrs struct {
	ctx     *context.Context
	message **mm_kafka.DLQMessage
	topic   *string
}

// ProducerMockSendToDLQResults contains results of the Producer.SendToDLQ
type ProducerMockSendToDLQResults struct {
	err error
}

// ProducerMockSendToDLQOrigins contains origins of expectations of the Producer.SendToDLQ
type ProducerMockSendToDLQExpectationOrigins struct {
	origin        string
	originCtx     string
	originMessage string
	originTopic   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendToDLQ *mProducerMockSendToDLQ) Optional() *mProducerMockSendToDLQ {
	mmSendToDLQ.optional = true
	return mmSendToDLQ
}

// Expect sets up expected params for Producer.SendToDLQ
func (mmSendToDLQ *mProducerMockSendToDLQ) Expect(ctx context.Context, message *mm_kafka.DLQMessage, topic string) *mProducerMockSendToDLQ {
	if mmSendToDLQ.mock.funcSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Set")
	}

	if mmSendToDLQ.defaultExpectation == nil {
		mmSendToDLQ.defaultExpectation = &ProducerMockSendToDLQExpectation{}
	}

	if mmSendToDLQ.defaultExpectation.paramPtrs != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by ExpectParams functions")
	}

	mmSendToDLQ.defaultExpectation.params = &ProducerMockSendToDLQParams{ctx, message, topic}
	mmSendToDLQ.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendToDLQ.expectations {
		if minimock.Equal(e.params, mmSendToDLQ.defaultExpectation.params) {
			mmSendToDLQ.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendToDLQ.defaultExpectation.params)
		}
	}

	return mmSendToDLQ
}

// ExpectCtxParam1 sets up expected param ctx for Producer.SendToDLQ
func (mmSendToDLQ *mProducerMockSendToDLQ) ExpectCtxParam1(ctx context.Context) *mProducerMockSendToDLQ {
	if mmSendToDLQ.mock.funcSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Set")
	}

	if mmSendToDLQ.defaultExpectation == nil {
		mmSendToDLQ.defaultExpectation = &ProducerMockSendToDLQExpectation{}
	}

	if mmSendToDLQ.defaultExpectation.params != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Expect")
	}

	if mmSendToDLQ.defaultExpectation.paramPtrs == nil {
		mmSendToDLQ.defaultExpectation.paramPtrs = &ProducerMockSendToDLQParamPtrs{}
	}
	mmSendToDLQ.defaultExpectation.paramPtrs.ctx = &ctx
	mmSendToDLQ.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSendToDLQ
}

// ExpectMessageParam2 sets up expected param message for Producer.SendToDLQ
func (mmSendToDLQ *mProducerMockSendToDLQ) ExpectMessageParam2(message *mm_kafka.DLQMessage) *mProducerMockSendToDLQ {
	if mmSendToDLQ.mock.funcSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Set")
	}

	if mmSendToDLQ.defaultExpectation == nil {
		mmSendToDLQ.defaultExpectation = &ProducerMockSendToDLQExpectation{}
	}

	if mmSendToDLQ.defaultExpectation.params != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Expect")
	}

	if mmSendToDLQ.defaultExpectation.paramPtrs == nil {
		mmSendToDLQ.defaultExpectation.paramPtrs = &ProducerMockSendToDLQParamPtrs{}
	}
	mmSendToDLQ.defaultExpectation.paramPtrs.message = &message
	mmSendToDLQ.defaultExpectation.expectationOrigins.originMessage = minimock.CallerInfo(1)

	return mmSendToDLQ
}

// ExpectTopicParam3 sets up expected param topic for Producer.SendToDLQ
func (mmSendToDLQ *mProducerMockSendToDLQ) ExpectTopicParam3(topic string) *mProducerMockSendToDLQ {
	if mmSendToDLQ.mock.funcSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Set")
	}

	if mmSendToDLQ.defaultExpectation == nil {
		mmSendToDLQ.defaultExpectation = &ProducerMockSendToDLQExpectation{}
	}

	if mmSendToDLQ.defaultExpectation.params != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Expect")
	}

	if mmSendToDLQ.defaultExpectation.paramPtrs == nil {
		mmSendToDLQ.defaultExpectation.paramPtrs = &ProducerMockSendToDLQParamPtrs{}
	}
	mmSendToDLQ.defaultExpectation.paramPtrs.topic = &topic
	mmSendToDLQ.defaultExpectation.expectationOrigins.originTopic = minimock.CallerInfo(1)

	return mmSendToDLQ
}

// Inspect accepts an inspector function that has same arguments as the Producer.SendToDLQ
func (mmSendToDLQ *mProducerMockSendToDLQ) Inspect(f func(ctx context.Context, message *mm_kafka.DLQMessage, topic string)) *mProducerMockSendToDLQ {
	if mmSendToDLQ.mock.inspectFuncSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("Inspect function is already set for ProducerMock.SendToDLQ")
	}

	mmSendToDLQ.mock.inspectFuncSendToDLQ = f

	return mmSendToDLQ
}

// Return sets up results that will be returned by Producer.SendToDLQ
func (mmSendToDLQ *mProducerMockSendToDLQ) Return(err error) *ProducerMock {
	if mmSendToDLQ.mock.funcSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Set")
	}

	if mmSendToDLQ.defaultExpectation == nil {
		mmSendToDLQ.defaultExpectation = &ProducerMockSendToDLQExpectation{mock: mmSendToDLQ.mock}
	}
	mmSendToDLQ.defaultExpectation.results = &ProducerMockSendToDLQResults{err}
	mmSendToDLQ.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendToDLQ.mock
}

// Set uses given function f to mock the Producer.SendToDLQ method
func (mmSendToDLQ *mProducerMockSendToDLQ) Set(f func(ctx context.Context, message *mm_kafka.DLQMessage, topic string) (err error)) *ProducerMock {
	if mmSendToDLQ.defaultExpectation != nil {
		mmSendToDLQ.mock.t.Fatalf("Default expectation is already set for the Producer.SendToDLQ method")
	}

	if len(mmSendToDLQ.expectations) > 0 {
		mmSendToDLQ.mock.t.Fatalf("Some expectations are already set for the Producer.SendToDLQ method")
	}

	mmSendToDLQ.mock.funcSendToDLQ = f
	mmSendToDLQ.mock.funcSendToDLQOrigin = minimock.CallerInfo(1)
	return mmSendToDLQ.mock
}

// When sets expectation for the Producer.SendToDLQ which will trigger the result defined by the following
// Then helper
func (mmSendToDLQ *mProducerMockSendToDLQ) When(ctx context.Context, message *mm_kafka.DLQMessage, topic string) *ProducerMockSendToDLQExpectation {
	if mmSendToDLQ.mock.funcSendToDLQ != nil {
		mmSendToDLQ.mock.t.Fatalf("ProducerMock.SendToDLQ mock is already set by Set")
	}

	expectation := &ProducerMockSendToDLQExpectation{
		mock:               mmSendToDLQ.mock,
		params:             &ProducerMockSendToDLQParams{ctx, message, topic},
		expectationOrigins: ProducerMockSendToDLQExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendToDLQ.expectations = append(mmSendToDLQ.expectations, expectation)
	return expectation
}

// Then sets up Producer.SendToDLQ return parameters for the expectation previously defined by the When method
func (e *ProducerMockSendToDLQExpectation) Then(err error) *ProducerMock {
	e.results = &ProducerMockSendToDLQResults{err}
	return e.mock
}

// Times sets number of times Producer.SendToDLQ should be invoked
func (mmSendToDLQ *mProducerMockSendToDLQ) Times(n uint64) *mProducerMockSendToDLQ {
	if n == 0 {
		mmSendToDLQ.mock.t.Fatalf("Times of ProducerMock.SendToDLQ mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendToDLQ.expectedInvocations, n)
	mmSendToDLQ.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendToDLQ
}

func (mmSendToDLQ *mProducerMockSendToDLQ) invocationsDone() bool {
	if len(mmSendToDLQ.expectations) == 0 && mmSendToDLQ.defaultExpectation == nil && mmSendToDLQ.mock.funcSendToDLQ == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendToDLQ.mock.afterSendToDLQCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendToDLQ.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendToDLQ implements mm_kafka.Producer
func (mmSendToDLQ *ProducerMock) SendToDLQ(ctx context.Context, message *mm_kafka.DLQMessage, topic string) (err error) {
	mm_atomic.AddUint64(&mmSendToDLQ.beforeSendToDLQCounter, 1)
	defer mm_atomic.AddUint64(&mmSendToDLQ.afterSendToDLQCounter, 1)

	mmSendToDLQ.t.Helper()

	if mmSendToDLQ.inspectFuncSendToDLQ != nil {
		mmSendToDLQ.inspectFuncSendToDLQ(ctx, message, topic)
	}

	mm_params := ProducerMockSendToDLQParams{ctx, message, topic}

	// Record call args
	mmSendToDLQ.SendToDLQMock.mutex.Lock()
	mmSendToDLQ.SendToDLQMock.callArgs = append(mmSendToDLQ.SendToDLQMock.callArgs, &mm_params)
	mmSendToDLQ.SendToDLQMock.mutex.Unlock()

	for _, e := range mmSendToDLQ.SendToDLQMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendToDLQ.SendToDLQMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendToDLQ.SendToDLQMock.defaultExpectation.Counter, 1)
		mm_want := mmSendToDLQ.SendToDLQMock.defaultExpectation.params
		mm_want_ptrs := mmSendToDLQ.SendToDLQMock.defaultExpectation.paramPtrs

		mm_got := ProducerMockSendToDLQParams{ctx, message, topic}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSendToDLQ.t.Errorf("ProducerMock.SendToDLQ got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendToDLQ.SendToDLQMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.message != nil && !minimock.Equal(*mm_want_ptrs.message, mm_got.message) {
				mmSendToDLQ.t.Errorf("ProducerMock.SendToDLQ got unexpected parameter message, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendToDLQ.SendToDLQMock.defaultExpectation.expectationOrigins.originMessage, *mm_want_ptrs.message, mm_got.message, minimock.Diff(*mm_want_ptrs.message, mm_got.message))
			}

			if mm_want_ptrs.topic != nil && !minimock.Equal(*mm_want_ptrs.topic, mm_got.topic) {
				mmSendToDLQ.t.Errorf("ProducerMock.SendToDLQ got unexpected parameter topic, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendToDLQ.SendToDLQMock.defaultExpectation.expectationOrigins.originTopic, *mm_want_ptrs.topic, mm_got.topic, minimock.Diff(*mm_want_ptrs.topic, mm_got.topic))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendToDLQ.t.Errorf("ProducerMock.SendToDLQ got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendToDLQ.SendToDLQMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendToDLQ.SendToDLQMock.defaultExpectation.results
		if mm_results == nil {
			mmSendToDLQ.t.Fatal("No results are set for the ProducerMock.SendToDLQ")
		}
		return (*mm_results).err
	}
	if mmSendToDLQ.funcSendToDLQ != nil {
		return mmSendToDLQ.funcSendToDLQ(ctx, message, topic)
	}
	mmSendToDLQ.t.Fatalf("Unexpected call to ProducerMock.SendToDLQ. %v %v %v", ctx, message, topic)
	return
}

// SendToDLQAfterCounter returns a count of finished ProducerMock.SendToDLQ invocations
func (mmSendToDLQ *ProducerMock) SendToDLQAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendToDLQ.afterSendToDLQCounter)
}

// SendToDLQBeforeCounter returns a count of ProducerMock.SendToDLQ invocations
func (mmSendToDLQ *ProducerMock) SendToDLQBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendToDLQ.beforeSendToDLQCounter)
}

// Calls returns a list of arguments used in each call to ProducerMock.SendToDLQ.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendToDLQ *mProducerMockSendToDLQ) Calls() []*ProducerMockSendToDLQParams {
	mmSendToDLQ.mutex.RLock()

	argCopy := make([]*ProducerMockSendToDLQParams, len(mmSendToDLQ.callArgs))
	copy(argCopy, mmSendToDLQ.callArgs)

	mmSendToDLQ.mutex.RUnlock()

	return argCopy
}

// MinimockSendToDLQDone returns true if the count of the SendToDLQ invocations corresponds
// the number of defined expectations
func (m *ProducerMock) MinimockSendToDLQDone() bool {
	if m.SendToDLQMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendToDLQMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendToDLQMock.invocationsDone()
}

// MinimockSendToDLQInspect logs each unmet expectation
func (m *ProducerMock) MinimockSendToDLQInspect() {
	for _, e := range m.SendToDLQMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProducerMock.SendToDLQ at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendToDLQCounter := mm_atomic.LoadUint64(&m.afterSendToDLQCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendToDLQMock.defaultExpectation != nil && afterSendToDLQCounter < 1 {
		if m.SendToDLQMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProducerMock.SendToDLQ at\n%s", m.SendToDLQMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProducerMock.SendToDLQ at\n%s with params: %#v", m.SendToDLQMock.defaultExpectation.expectationOrigins.origin, *m.SendToDLQMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendToDLQ != nil && afterSendToDLQCounter < 1 {
		m.t.Errorf("Expected call to ProducerMock.SendToDLQ at\n%s", m.funcSendToDLQOrigin)
	}

	if !m.SendToDLQMock.invocationsDone() && afterSendToDLQCounter > 0 {
		m.t.Errorf("Expected %d calls to ProducerMock.SendToDLQ at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendToDLQMock.expectedInvocations), m.SendToDLQMock.expectedInvocationsOrigin, afterSendToDLQCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProducerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCloseInspect()

			m.MinimockSendToDLQInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProducerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProducerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCloseDone() &&
		m.MinimockSendToDLQDone()
}
